language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
env:
- TRAVIS_NODE_VERSION="6.3"
services:
- postgresql
install:
- npm install
before_script:
- psql -c 'create database "todos-test";' -U postgres
- sequelize db:migrate
script:
- npm test
- "./node_modules/.bin/grunt collect_static"

